CREATE TABLE users (

    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(64 CHARACTERS) NOT NULL,
    password VARCHAR(64 CHARACTERS) NOT NULL,
    name VARCHAR(64 CHARACTERS) NOT NULL,
    surname VARCHAR(64 CHARACTERS) NOT NULL,
    CONSTRAINT unique_email_constraint UNIQUE (email)
);